### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by PANOSSS1980** [7even/itunes#1]
MAN I NEED YOUR HELP PLEASE!!!I HAVE ONE PAGE BUT UNFORTUNATELY I CANT SHOW UNLIMITED RESULTS!!!MAX 200...CAN YOU HELP ME PLEASE INCREASE UNLIMITED???

**Comment by 7even** [comment]
I don't understand what you're talking about. Unlimited results of what?

**Comment by PANOSSS1980** [comment]
MAN MY PAGE SHOW SONGS FROM ITUNES,BUT UNFORTUNATELY SHOWS JUST 200 RESULTS!!!COULD YOU HELP ME PLEASE SHOW UNLIMITED???

**Comment by 7even** [comment]
What page? Does it have anything to do with this project?

**Comment by PANOSSS1980** [comment]
HELLO MAN!!AND HAPPY EASTER.MAN I HAVE ONE PAGE WHERE USE API FROM ITUNES FOR MUSIC RESULTS...BUT I CANT INCREASE UNLIMITED RESULTS...JUST 200...COULD YOU HELP ME PLEASE INCREASE UNLIMITED???

**Comment by 7even** [comment]
Sorry, I'm not familiar with the iTunes API - this project is all about parsing the iTunes library's XML file - so unfortunately I can't help you. Happy Easter.
